### ISSUE TITLE
인기 상권 목록조회 API 구현

### ISSUE THREAD

**Issue by jinlee1703** [Two-Year-Gap/smaap-was#33]
## Description

특정 조건별 인기 상권 목록을 반환하는 API 구현 필요성 대두

## Task

- [ ] 점포 수가 많은 상권
- [x] 매출액이 많은 상권
- [x] 유동 인구가 많은 상권
- [x] 거주 인구가 많은 상권
