### ISSUE TITLE
Spring Boot Entity 구현

### ISSUE THREAD

**Issue by jinlee1703** [Two-Year-Gap/smaap-was#5]
## Description

서비스 도메인 관련 Spring Boot Entity 구현

<img width="991" alt="image" src="https://github.com/user-attachments/assets/914d64f4-238d-4888-8725-06c9834ec5f0">

## Task

- [x] `school/entity/School.java`
- [x] `welfare/entity/WelfareInfra`
- [x] `business/entity/Business.java`
- [x] `business/entity/Store.java`
- [x] `region/entity/Region.java`
- [x] `region/entity/District.java`
- [x] `region/entity/Neighborhood.java`
